**Model SELECTION Cross Validation Check**



In [ ]:
from sklearn import datasets , linear_model
from sklearn.model_selection import cross_val_score

In [ ]:
diabetes = datasets.load_diabetes()
X= diabetes.data[:150]
Y= diabetes.target[:150]
lasso= linear_model.Lasso()
print(cross_val_score(lasso,X,Y,cv=3))

[0.33150734 0.08022311 0.03531764]


#Google collab basics

**Collab Basics**

**Specification**

In [ ]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0x1
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 b

In [ ]:
!cat /proc/meminfo

MemTotal:       13305332 kB
MemFree:        10705100 kB
MemAvailable:   12492224 kB
Buffers:           87016 kB
Cached:          1834508 kB
SwapCached:            0 kB
Active:           985580 kB
Inactive:        1376100 kB
Active(anon):     402896 kB
Inactive(anon):      420 kB
Active(file):     582684 kB
Inactive(file):  1375680 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               332 kB
Writeback:             0 kB
AnonPages:        440300 kB
Mapped:           239608 kB
Shmem:              1164 kB
KReclaimable:     140460 kB
Slab:             187488 kB
SReclaimable:     140460 kB
SUnreclaim:        47028 kB
KernelStack:        4320 kB
PageTables:         6064 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6652664 kB
Committed_AS:    3231680 kB
VmallocTotal:   34359738367 kB
VmallocUsed:        6720 kB
VmallocChunk:          0 kB
Percpu:          

In [ ]:
! ls

Demo.txt  sample_data


In [ ]:
print("Hello world")

Hello world


**Function Description**

In [ ]:
print("Hello world")

Hello world


In [ ]:
print?

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
train_test_split?

**Library** **Installation**

In [ ]:
!pip install matplotlib

#Python Basics

In [ ]:
#comment

variables

In [ ]:
a = 5
print(a)

5


In [ ]:
a = int(input('Give the first number'))
b= int(input('Give the second number'))
sum=a+b
print(sum)

Give the first number10
Give the second number20
30


In [ ]:
list_1 = [1,2,3,4,5]
print(list_1)

[1, 2, 3, 4, 5]


In [ ]:
type(list_1)

list

In [ ]:
print(list_1[3])

4


In [ ]:
print(list_1[1:4])

[2, 3, 4]


In [ ]:
list_1.append(11)
print(list_1)

[1, 2, 3, 4, 5, 11]


In [ ]:
del list_1[4]
print(list_1)

[1, 2, 3, 4]


In [ ]:
my_list =[1,2,3,4,5]
new_list=[]
for i in my_list:
  j=i*5
  new_list.append(j)

print(new_list)

[5, 10, 15, 20, 25]


In [ ]:
empty_tuples = ()
print(empty_tuples)

()


In [ ]:
tuple_1=(1,2,3,4,5.5,'word')
print(tuple_1)

(1, 2, 3, 4, 5.5, 'word')


In [ ]:
my_list=[5,6,7,8]
tup=tuple(my_list)
print(tup)
type(tup)

(5, 6, 7, 8)


tuple

set

In [ ]:
my_list=[5,2,8,3,4,'Monday',4.5]
my_set= set(my_list)
print(my_set)
type(my_set)

{2, 3, 4, 5, 4.5, 8, 'Monday'}


set

In [ ]:
set_1={1,2,2,3,4,3,5} #set doesn't have index
print(set_1)

{1, 2, 3, 4, 5}


In [ ]:
set_2={1,2,3,4,5}
set_3={2,3,5,6,7,8}
union_set=set_2|set_3
intersection_set=set_2 & set_3
print(union_set)
print(intersection_set)

{1, 2, 3, 4, 5, 6, 7, 8}
{2, 3, 5}


dictionary

In [ ]:
cricket = {'India':'blue','Australia':'Yellow','South Africa':'Green','New Zealand':'black'}
print(cricket)
type(cricket)

{'India': 'blue', 'Australia': 'Yellow', 'South Africa': 'Green', 'New Zealand': 'black'}


dict

In [ ]:
print(cricket['Australia'])

Yellow


In [ ]:
cricket['Australia'] = 'green'
print(cricket)

{'India': 'blue', 'Australia': 'green', 'South Africa': 'Green', 'New Zealand': 'black'}


In [ ]:
for i in range(5):
  print("DS")

DS
DS
DS
DS
DS


In [ ]:
superheroes = ['Iron man','Hulk','Thor','Superman','Batman']
print(superheroes[0])

Iron man


In [ ]:
for i in superheroes:
  print(i)

Iron man
Hulk
Thor
Superman
Batman


In [ ]:
l1=[1,2,3,4,5]
l2=[]
for i in l1:
  j=i*5
  l2.append(j)
print(l2)

[5, 10, 15, 20, 25]


In [ ]:
i=0
sum=0
count = 0
while(sum<100):
  sum = sum+i
  i=i+10
  count=count+1
print(sum) 
print(count)


100
5


#NUMPY BASICS

Numerical Python

List to numpy array conversion

In [1]:
a = [1,2,3] 


In [2]:
type(a)

list

In [3]:
import numpy as np


In [4]:
a=np.array(a)
print(a)

[1 2 3]


In [5]:
type(a)

numpy.ndarray

In [6]:
np.array?

In [7]:
a = [3,4,5]
b = np.asarray(a,float)


In [8]:
print(b)

[3. 4. 5.]


Creating Numpy arrays

In [9]:
x=np.array([7,8,9,10])
print(x)
type(x)

[ 7  8  9 10]


numpy.ndarray

In [10]:
print(x[0])

7


In [11]:
x[0]=10

In [12]:
print(x)

[10  8  9 10]


In [14]:
y=np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


In [15]:
print(y[0,0])
print(y[1,0])

1
4


In [16]:
#shape of the array
print(x.shape)
print(y.shape)

(4,)
(2, 3)


In [18]:
#create null matrix
null = np.zeros((3,3))
print(null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
#identity matrix
identity = np.eye(3,3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
#array of all array as 1
one = np.ones((2,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
#array with constant element
constant = np.full((3,4),8)
print(constant)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [23]:
#random set of numbers
random_array = np.random.random((3,3))
print(random_array)

[[0.05911952 0.34725868 0.46305062]
 [0.80781536 0.21641288 0.31193698]
 [0.84494155 0.72121614 0.19268016]]


In [25]:
#random int values
integer_random = np.random.randint(1,10,(3,10))
print(integer_random)

[[1 6 3 9 2 5 4 1 4 9]
 [6 4 1 4 5 5 9 7 8 1]
 [5 8 4 6 9 3 5 4 9 9]]


In [26]:
#transpose
array = np.random.random((3,3))
print(array)

[[0.70500503 0.41208693 0.48004651]
 [0.61758666 0.52611686 0.80704335]
 [0.6105169  0.19241444 0.09089172]]


In [27]:
transposed_array = array.T
print(transposed_array)

[[0.70500503 0.61758666 0.6105169 ]
 [0.41208693 0.52611686 0.19241444]
 [0.48004651 0.80704335 0.09089172]]


In [29]:
#Reshaping
A = np.random.random((3,4))
print(A)

[[0.60267925 0.19069883 0.96725491 0.64665823]
 [0.47018772 0.68438014 0.47706855 0.33301458]
 [0.65278459 0.95378631 0.86494182 0.5344633 ]]


In [30]:
reshaped_array = A.reshape(12,1)
print(reshaped_array)

[[0.60267925]
 [0.19069883]
 [0.96725491]
 [0.64665823]
 [0.47018772]
 [0.68438014]
 [0.47706855]
 [0.33301458]
 [0.65278459]
 [0.95378631]
 [0.86494182]
 [0.5344633 ]]


Slicing taking elements from one index to another index

In [31]:
#Slicing
array = np.array([1,2,3,4,5,6,7,8])
print(array)

[1 2 3 4 5 6 7 8]


In [32]:
print(array[1:5])

[2 3 4 5]


In [33]:
print(array[:5])

[1 2 3 4 5]


In [34]:
print(array[4:])

[5 6 7 8]


In [36]:
print(array)
print(array[1:6:2])

[1 2 3 4 5 6 7 8]
[2 4 6]


In [39]:
print(array[::3])

[1 4 7]


Slicing in 2D array

In [40]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [41]:
print(a[1,1:4])

[ 8  9 10]


In [42]:
print(a[:,1:3])

[[2 3]
 [8 9]]


#PANDAS

pandas Dataframe

In [43]:
import pandas as pd

In [44]:
#creating empty dataframe
df= pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [45]:
type(df)

pandas.core.frame.DataFrame

In [46]:
super_hero_list = ['Iron Man','Thor','Super Man','Flash']
print(super_hero_list)
print(type(super_hero_list))

['Iron Man', 'Thor', 'Super Man', 'Flash']
<class 'list'>


In [47]:
#convert list to dataframe
df = pd.DataFrame(super_hero_list)
print(df)

           0
0   Iron Man
1       Thor
2  Super Man
3      Flash


In [48]:
df = pd.DataFrame(super_hero_list,columns=['Super Hero'])
print(df)

  Super Hero
0   Iron Man
1       Thor
2  Super Man
3      Flash


Iris Dataset

In [49]:
#Loading csv file to pandas DAtaframe
df = pd.read_csv('/content/Iris.csv')

In [50]:
df.head() #5 rows of dataframe

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [51]:
df.tail()

Id  SepalLengthCm  ...  PetalWidthCm         Species
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[5 rows x 6 columns]

In [52]:
#drop a column 
df_id_drop = df.drop(['Id'],axis=1)
print(df_id_drop)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]


In [53]:
df_id_drop = df.drop([149],axis=0)
print(df_id_drop)

      Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
144  145            6.7  ...           2.5  Iris-virginica
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica

[149 rows x 6 columns]


In [54]:
print(len(df_id_drop))

149


In [55]:
print(df_id_drop.shape)

(149, 6)


In [56]:
df_id_drop.loc[3] #get a specific data point

Id                         4
SepalLengthCm            4.6
SepalWidthCm             3.1
PetalLengthCm            1.5
PetalWidthCm             0.2
Species          Iris-setosa
Name: 3, dtype: object

In [57]:
df_id_drop.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  149.000000     149.000000    149.000000     149.000000    149.000000
mean    75.000000       5.842953      3.054362       3.749664      1.194631
std     43.156691       0.830846      0.435034       1.766911      0.764127
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.000000       5.100000      2.800000       1.600000      0.300000
50%     75.000000       5.800000      3.000000       4.300000      1.300000
75%    112.000000       6.400000      3.300000       5.100000      1.800000
max    149.000000       7.900000      4.400000       6.900000      2.500000

In [59]:
df_id_drop.groupby('Species').mean()

Id  SepalLengthCm  ...  PetalLengthCm  PetalWidthCm
Species                                ...                             
Iris-setosa       25.5       5.006000  ...       1.464000      0.244000
Iris-versicolor   75.5       5.936000  ...       4.260000      1.326000
Iris-virginica   125.0       6.602041  ...       5.561224      2.030612

[3 rows x 5 columns]

#Important Python Libraries

In [ ]:
#scikit learn : various ML program eg Logistic reg
#Tensor Flow : Deep Learning
#pytorch : Deep Learning developed by FB
#Open CV : Image Processing